apiVersion: v1
kind: Secret
metadata:
  name: demo-db
type: servicebinding.io/postgresql
stringData:
  type: "mysql"
  provider: "mysql"
  host: "<RDS_ENDPOINT>"
  port: "3306"
  database: "petclinic"
  username: "admin"
  password: "<YOUR_PASSWORD>"