---
apiVersion: v1
kind: Service
metadata:
  name: petclinic
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: petclinic

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic
  labels:
    app: petclinic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: petclinic
  template:
    metadata:
      labels:
        app: petclinic
    spec:
      containers:
        - name: workload
          image: 708309164311.dkr.ecr.us-east-1.amazonaws.com/petclinic:latest
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: mysql
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://<RDS_ENDPOINT>:3306/petclinic"
            - name: SPRING_DATASOURCE_USERNAME
              value: "admin"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "<YOUR_PASSWORD>"
            - name: JAVA_TOOL_OPTIONS
              value: "-XX:MaxMetaspaceSize=100M -XX:ReservedCodeCacheSize=100M -Xss512k -XX:MaxDirectMemorySize=10M -Xmx256m"
            - name: SPRING_APPLICATION_JSON
              value: |
                {
                  "management.endpoint.health.probes.add-additional-paths": true
                }
          ports:
            - name: http
              containerPort: 8080
          livenessProbe:
            httpGet:
              path: /livez
              port: http
          readinessProbe:
            httpGet:
              path: /readyz
              port: http
      volumes:
        - name: binding
          projected:
            sources:
              - secret:
                  name: demo-db