name: "JFrog Maven Build"
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
         
      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v4
        env:  
          JF_URL: ${{ vars.JF_URL }}
          JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}
           
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set CLI Config
        run: |
          jf mvnc \
            --repo-resolve-releases=spring-petclinic-libs-snapshot \
            --repo-resolve-snapshots=spring-petclinic-libs-snapshot \
            --repo-deploy-releases=spring-petclinic-libs-snapshot-local \
            --repo-deploy-snapshots=spring-petclinic-libs-snapshot-local
           
      - name: Build and Install
        # Use 'jf mvn' to trigger the JFrog Build Info extractor
        # We keep the SSL bypass flags to handle the certificate issue
        run: |
          jf mvn clean install -U \
            -Dmaven.wagon.http.ssl.insecure=true \
            -Dmaven.wagon.http.ssl.allowall=true
         
      - name: Publish Build info
        run: |
          jf rt build-collect-env
          jf rt build-add-git
          jf rt build-publish
